# Generated by Django 5.2.4 on 2025-07-24 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboSueldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('enero', 'Enero'), ('febrero', 'Febrero'), ('marzo', 'Marzo'), ('abril', 'Abril'), ('mayo', 'Mayo'), ('junio', 'Junio'), ('julio', 'Julio'), ('agosto', 'Agosto'), ('septiembre', 'Septiembre'), ('octubre', 'Octubre'), ('noviembre', 'Noviembre'), ('diciembre', 'Diciembre')], max_length=20)),
                ('anio', models.IntegerField()),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('archivo_pdf', models.FileField(help_text='PDF del recibo original para firmar', upload_to='recibos_sueldo/')),
                ('archivo_pdf_centromedica', models.FileField(blank=True, help_text='PDF firmado por Centromédica que el empleado visualiza', null=True, upload_to='recibos_centromedica/')),
                ('archivo_firmado', models.FileField(blank=True, help_text='PDF firmado digitalmente por el empleado', null=True, upload_to='recibos_firmados/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Firma'), ('observado', 'Observado por Empleado'), ('respondido', 'Observación Respondida por RRHH'), ('firmado', 'Firmado'), ('vencido', 'Vencido'), ('no_encontrado', 'Recibo No Encontrado')], default='pendiente', max_length=20)),
                ('observaciones_empleado', models.TextField(blank=True, help_text='Observaciones del empleado sobre el recibo')),
                ('fecha_observacion', models.DateTimeField(blank=True, help_text='Fecha cuando el empleado hizo la observación', null=True)),
                ('observaciones_rrhh', models.TextField(blank=True, help_text='Respuesta de RRHH a las observaciones')),
                ('fecha_respuesta_rrhh', models.DateTimeField(blank=True, help_text='Fecha de respuesta de RRHH', null=True)),
                ('sueldo_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descuentos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sueldo_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos_sueldo', to='empleados.empleado')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_respondidas', to=settings.AUTH_USER_MODEL)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recibo de Sueldo',
                'verbose_name_plural': 'Recibos de Sueldo',
                'ordering': ['anio', 'periodo'],
                'unique_together': {('empleado', 'periodo', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='FirmaRecibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_firma', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('tipo_firma', models.CharField(choices=[('conforme', 'Conforme'), ('observado', 'Con Observaciones Previas')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
                ('recibo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma_auditoria', to='recibos.recibosueldo')),
            ],
            options={
                'verbose_name': 'Firma de Recibo',
                'verbose_name_plural': 'Firmas de Recibos',
                'ordering': ['-fecha_firma'],
            },
        ),
    ]
