# Generated by Django 5.2.4 on 2025-07-03 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0005_remove_obrasocialempleado_numero_afiliado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboSueldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('enero', 'Enero'), ('febrero', 'Febrero'), ('marzo', 'Marzo'), ('abril', 'Abril'), ('mayo', 'Mayo'), ('junio', 'Junio'), ('julio', 'Julio'), ('agosto', 'Agosto'), ('septiembre', 'Septiembre'), ('octubre', 'Octubre'), ('noviembre', 'Noviembre'), ('diciembre', 'Diciembre')], max_length=20)),
                ('anio', models.IntegerField()),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('archivo_pdf', models.FileField(help_text='PDF del recibo original', upload_to='recibos_sueldo/')),
                ('archivo_firmado', models.FileField(blank=True, help_text='PDF firmado digitalmente', null=True, upload_to='recibos_firmados/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Firma'), ('firmado', 'Firmado'), ('firmado_disconforme', 'Firmado en Disconformidad'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('observaciones_empleado', models.TextField(blank=True, help_text='Observaciones del empleado al firmar en disconformidad')),
                ('observaciones_rrhh', models.TextField(blank=True, help_text='Observaciones de RRHH')),
                ('sueldo_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descuentos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sueldo_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos_sueldo', to='empleados.empleado')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recibo de Sueldo',
                'verbose_name_plural': 'Recibos de Sueldo',
                'ordering': ['-anio', '-periodo'],
                'unique_together': {('empleado', 'periodo', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='FirmaRecibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_firma', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('tipo_firma', models.CharField(choices=[('conforme', 'Conforme'), ('disconforme', 'Disconforme')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
                ('recibo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma_auditoria', to='recibos.recibosueldo')),
            ],
            options={
                'verbose_name': 'Firma de Recibo',
                'verbose_name_plural': 'Firmas de Recibos',
                'ordering': ['-fecha_firma'],
            },
        ),
    ]
