# Generated by Django 5.2.4 on 2025-07-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('recibos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recibosueldo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recibosueldo',
            name='tipo_recibo',
            field=models.CharField(choices=[('sueldo', 'Recibo de Sueldo'), ('sac_1', 'SAC Primer Semestre'), ('sac_2', 'SAC Segundo Semestre')], default='sueldo', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='recibosueldo',
            unique_together={('empleado', 'periodo', 'anio', 'tipo_recibo')},
        ),
    ]
