# Generated by Django 5.2.4 on 2025-07-03 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recibosueldo',
            name='fecha_observacion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando el empleado hizo la observación', null=True),
        ),
        migrations.AddField(
            model_name='recibosueldo',
            name='fecha_respuesta_rrhh',
            field=models.DateTimeField(blank=True, help_text='Fecha de respuesta de RRHH', null=True),
        ),
        migrations.AddField(
            model_name='recibosueldo',
            name='respondido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_respondidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='firmarecibo',
            name='tipo_firma',
            field=models.CharField(choices=[('conforme', 'Conforme'), ('observado', 'Con Observaciones Previas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recibosueldo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Firma'), ('observado', 'Observado por Empleado'), ('respondido', 'Observación Respondida por RRHH'), ('firmado', 'Firmado'), ('vencido', 'Vencido')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='recibosueldo',
            name='observaciones_empleado',
            field=models.TextField(blank=True, help_text='Observaciones del empleado sobre el recibo'),
        ),
        migrations.AlterField(
            model_name='recibosueldo',
            name='observaciones_rrhh',
            field=models.TextField(blank=True, help_text='Respuesta de RRHH a las observaciones'),
        ),
    ]
