# Generated by Django 5.2.4 on 2025-07-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0002_alter_recibosueldo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibosueldo',
            name='tipo_recibo',
            field=models.CharField(choices=[('sueldo', 'Sueldo'), ('sac_1', 'SAC 1'), ('sac_2', 'SAC 2')], default='sueldo', max_length=10),
        ),
    ]
