# Generated by Django 5.2.4 on 2025-07-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0002_recibosueldo_fecha_observacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recibosueldo',
            options={'ordering': ['anio', 'periodo'], 'verbose_name': 'Recibo de Sueldo', 'verbose_name_plural': 'Recibos de Sueldo'},
        ),
    ]
