# Generated by Django 5.2.4 on 2025-07-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0003_alter_recibosueldo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibosueldo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Firma'), ('observado', 'Observado por Empleado'), ('respondido', 'Observación Respondida por RRHH'), ('firmado', 'Firmado'), ('vencido', 'Vencido'), ('no_encontrado', 'Recibo No Encontrado')], default='pendiente', max_length=20),
        ),
    ]
