# Generated by Django 5.2.4 on 2025-07-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0004_alter_recibosueldo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibosueldo',
            name='archivo_pdf_centromedica',
            field=models.FileField(blank=True, help_text='PDF firmado por Centromédica que el empleado visualiza', null=True, upload_to='recibos_centromedica/'),
        ),
        migrations.AlterField(
            model_name='recibosueldo',
            name='archivo_firmado',
            field=models.FileField(blank=True, help_text='PDF firmado digitalmente por el empleado', null=True, upload_to='recibos_firmados/'),
        ),
        migrations.AlterField(
            model_name='recibosueldo',
            name='archivo_pdf',
            field=models.FileField(help_text='PDF del recibo original para firmar', upload_to='recibos_sueldo/'),
        ),
    ]
