# Generated by Django 5.2.4 on 2025-07-08 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaMasivaRecibos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('enero', 'Enero'), ('febrero', 'Febrero'), ('marzo', 'Marzo'), ('abril', 'Abril'), ('mayo', 'Mayo'), ('junio', 'Junio'), ('julio', 'Julio'), ('agosto', 'Agosto'), ('septiembre', 'Septiembre'), ('octubre', 'Octubre'), ('noviembre', 'Noviembre'), ('diciembre', 'Diciembre')], max_length=20)),
                ('anio', models.IntegerField()),
                ('archivo_pdf', models.FileField(help_text='PDF con todos los recibos del período', upload_to='recibos_masivos/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Procesamiento'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error en el Procesamiento')], default='pendiente', max_length=20)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('total_empleados', models.IntegerField(default=0, help_text='Total de empleados en el sistema')),
                ('recibos_generados', models.IntegerField(default=0, help_text='Recibos generados exitosamente')),
                ('errores_procesamiento', models.TextField(blank=True, help_text='Errores durante el procesamiento')),
                ('dias_vencimiento', models.IntegerField(default=30, help_text='Días para vencimiento desde la fecha de carga')),
                ('usuario_carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_recibos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carga Masiva de Recibos',
                'verbose_name_plural': 'Cargas Masivas de Recibos',
                'ordering': ['-fecha_carga'],
                'unique_together': {('periodo', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='LogProcesamientoRecibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo_empleado', models.CharField(max_length=20)),
                ('nombre_empleado', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('exitoso', 'Procesado Exitosamente'), ('error', 'Error en Procesamiento'), ('empleado_no_encontrado', 'Empleado No Encontrado'), ('datos_invalidos', 'Datos Inválidos')], max_length=25)),
                ('mensaje', models.TextField(help_text='Mensaje detallado del procesamiento')),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('carga_masiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_procesamiento', to='rrhh.cargamasivarecibos')),
            ],
            options={
                'verbose_name': 'Log de Procesamiento',
                'verbose_name_plural': 'Logs de Procesamiento',
                'ordering': ['-fecha_procesamiento'],
            },
        ),
    ]
