# Generated by Django 5.2.4 on 2025-07-08 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargamasivarecibos',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando fue validada la carga', null=True),
        ),
        migrations.AddField(
            model_name='cargamasivarecibos',
            name='validado',
            field=models.BooleanField(default=False, help_text='Si la carga fue validada por RRHH'),
        ),
        migrations.AddField(
            model_name='cargamasivarecibos',
            name='validado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que validó la carga', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_validadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargamasivarecibos',
            name='visible_empleados',
            field=models.BooleanField(default=False, help_text='Si los recibos son visibles para los empleados'),
        ),
    ]
