# Generated by Django 5.2.4 on 2025-07-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargamasivarecibos',
            name='tipo_recibo',
            field=models.CharField(choices=[('sueldo', 'Sueldo'), ('sac_1', 'SAC 1'), ('sac_2', 'SAC 2')], default='sueldo', max_length=10),
        ),
    ]
