# Generated by Django 5.2.4 on 2025-07-29 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_cargamasivarecibos_tipo_recibo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cargamasivarecibos',
            unique_together={('periodo', 'anio', 'tipo_recibo')},
        ),
    ]
