# Generated by Django 5.2.4 on 2025-07-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_cargamasivarecibos_fecha_validacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logprocesamientorecibo',
            name='estado',
            field=models.CharField(choices=[('exitoso', 'Procesado Exitosamente'), ('error', 'Error en Procesamiento'), ('empleado_no_encontrado', 'Empleado No Encontrado'), ('datos_invalidos', 'Datos Inválidos'), ('no_encontrado', 'Recibo No Encontrado en PDF')], max_length=25),
        ),
    ]
