# Generated by Django 5.2.4 on 2025-07-24 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_rrhh', models.BooleanField(default=False, help_text='Marcar si este usuario pertenece al área de RRHH y debe acceder al panel de gestión RRHH.', verbose_name='¿Es RRHH?')),
                ('legajo', models.CharField(max_length=20, unique=True)),
                ('numero_legajo', models.IntegerField(blank=True, help_text='Número de legajo para facilitar búsquedas', null=True)),
                ('dni', models.CharField(max_length=20)),
                ('cuil', models.CharField(blank=True, max_length=15)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('puesto', models.CharField(blank=True, max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('supervisor', models.CharField(blank=True, max_length=100)),
                ('tipo_contrato', models.CharField(choices=[('tiempo_completo', 'Tiempo completo'), ('tiempo_parcial', 'Tiempo parcial'), ('freelance', 'Freelance')], default='tiempo_completo', max_length=20)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_contrato', models.DateField(blank=True, null=True)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=100)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20)),
                ('relacion_emergencia', models.CharField(blank=True, max_length=50)),
                ('firma_imagen', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('firma_pin', models.CharField(blank=True, max_length=6)),
                ('debe_cambiar_password', models.BooleanField(default=False, help_text='Marcar si el usuario debe cambiar su contraseña en el próximo login', verbose_name='Debe cambiar contraseña')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='DomicilioEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(blank=True, max_length=100)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('piso', models.CharField(blank=True, max_length=10)),
                ('depto', models.CharField(blank=True, max_length=10)),
                ('barrio', models.CharField(blank=True, max_length=100)),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('entre_calles', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domicilio', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilios',
            },
        ),
        migrations.CreateModel(
            name='ActividadEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='FamiliarEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.CharField(max_length=20)),
                ('parentesco', models.CharField(choices=[('esposo/a', 'Esposo/a'), ('hijo/a', 'Hijo/a'), ('padre/madre', 'Padre/Madre'), ('hermano/a', 'Hermano/a'), ('otro', 'Otro')], max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Familiar',
                'verbose_name_plural': 'Familiares',
            },
        ),
        migrations.CreateModel(
            name='ObraSocialEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='obra_social', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Obra Social',
                'verbose_name_plural': 'Obras Sociales',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('domicilio', 'Cambio de Domicilio'), ('obra_social', 'Cambio de Obra Social')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('datos_antiguos', models.JSONField()),
                ('datos_nuevos', models.JSONField()),
                ('declaracion_jurada', models.TextField()),
                ('pdf_declaracion', models.FileField(blank=True, null=True, upload_to='declaraciones_juradas/')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='adjuntos_solicitudes/')),
                ('observaciones_rrhh', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio', to='empleados.empleado')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Cambio',
                'verbose_name_plural': 'Solicitudes de Cambio',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
