# Generated by Django 5.2.4 on 2025-07-03 04:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='obra_social',
        ),
        migrations.AddField(
            model_name='empleado',
            name='cuil',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='familiarempleado',
            name='apellido',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DomicilioEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(blank=True, max_length=100)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('piso', models.CharField(blank=True, max_length=10)),
                ('depto', models.CharField(blank=True, max_length=10)),
                ('barrio', models.CharField(blank=True, max_length=100)),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('entre_calles', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domicilio', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilios',
            },
        ),
        migrations.CreateModel(
            name='ObraSocialEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('numero_afiliado', models.CharField(blank=True, max_length=50)),
                ('plan', models.CharField(blank=True, max_length=100)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='obra_social', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Obra Social',
                'verbose_name_plural': 'Obras Sociales',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('domicilio', 'Cambio de Domicilio'), ('obra_social', 'Cambio de Obra Social')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('datos_antiguos', models.JSONField()),
                ('datos_nuevos', models.JSONField()),
                ('declaracion_jurada', models.TextField()),
                ('observaciones_rrhh', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio', to='empleados.empleado')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Cambio',
                'verbose_name_plural': 'Solicitudes de Cambio',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
