# Generated by Django 5.2.4 on 2025-07-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el empleado está activo. Los empleados inactivos no aparecen en las cargas masivas de recibos.', verbose_name='Empleado Activo'),
        ),
    ]
