# Generated by Django 5.2.4 on 2025-07-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_remove_empleado_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcambio',
            name='pdf_declaracion',
            field=models.FileField(blank=True, null=True, upload_to='declaraciones_juradas/'),
        ),
    ]
