# Generated by Django 5.2.4 on 2025-07-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_solicitudcambio_pdf_declaracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcambio',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='adjuntos_solicitudes/'),
        ),
    ]
