# Generated by Django 5.2.4 on 2025-07-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_solicitudcambio_archivo_adjunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obrasocialempleado',
            name='numero_afiliado',
        ),
        migrations.RemoveField(
            model_name='obrasocialempleado',
            name='plan',
        ),
    ]
