# Generated by Django 5.2.4 on 2025-07-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_remove_obrasocialempleado_numero_afiliado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='es_rrhh',
            field=models.BooleanField(default=False, help_text='Marcar si este usuario pertenece al área de RRHH y debe acceder al panel de gestión RRHH.', verbose_name='¿Es RRHH?'),
        ),
    ]
