# Generated by Django 5.2.4 on 2025-07-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_empleado_es_rrhh'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='numero_legajo',
            field=models.IntegerField(blank=True, help_text='Número de legajo para facilitar búsquedas', null=True),
        ),
    ]
