# Generated by Django 5.2.4 on 2025-07-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_empleado_numero_legajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='Marcar si el usuario debe cambiar su contraseña en el próximo login', verbose_name='Debe cambiar contraseña'),
        ),
    ]
