# Generated by Django 5.2.4 on 2025-07-24 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('requiere_aclaracion', 'Requiere Aclaración')], default='pendiente', max_length=20)),
                ('fecha_desde', models.DateField(blank=True, help_text='Fecha desde la cual es válido el documento', null=True)),
                ('fecha_hasta', models.DateField(blank=True, help_text='Fecha hasta la cual es válido el documento', null=True)),
                ('observaciones_rrhh', models.TextField(blank=True, help_text='Observaciones del área de RRHH')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='empleados.empleado')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='HistorialDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='documentos.documento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Documento',
                'verbose_name_plural': 'Historial de Documentos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Inasistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('tipo', models.CharField(choices=[('enfermedad', 'Enfermedad'), ('personal', 'Motivos Personales'), ('familiar', 'Familiar'), ('estudio', 'Estudio'), ('otro', 'Otro')], max_length=20)),
                ('estado', models.CharField(choices=[('injustificada', 'Injustificada'), ('pendiente', 'Pendiente Justificación'), ('justificada', 'Justificada')], default='injustificada', max_length=20)),
                ('motivo', models.TextField(blank=True, help_text='Descripción del motivo de la inasistencia')),
                ('observaciones_rrhh', models.TextField(blank=True, help_text='Observaciones del área de RRHH')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inasistencias_creadas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inasistencias', to='empleados.empleado')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inasistencias_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inasistencia',
                'verbose_name_plural': 'Inasistencias',
                'ordering': ['-fecha_desde'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='inasistencia',
            field=models.ForeignKey(blank=True, help_text='Inasistencia que justifica este documento (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='documentos.inasistencia'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.tipodocumento'),
        ),
    ]
