"""
Django settings for proyecto_rrhh project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v!x)u*u_#4lfhi_-se23===hc6%f8a&pfx!%!hwr#5#nulv%02'

# Detectar entorno automáticamente
IS_PYTHONANYWHERE = 'PYTHONANYWHERE_DOMAIN' in os.environ
IS_RENDER = 'RENDER' in os.environ
IS_DEVELOPMENT = not (IS_PYTHONANYWHERE or IS_RENDER)

if IS_PYTHONANYWHERE:
    # Configuración para PythonAnywhere
    DEBUG = False
    ALLOWED_HOSTS = [os.environ.get('PYTHONANYWHERE_DOMAIN', 'localhost')]
    CSRF_TRUSTED_ORIGINS = [f"https://{os.environ.get('PYTHONANYWHERE_DOMAIN', 'localhost')}"]
    
    # Media y static files para PythonAnywhere
    MEDIA_URL = '/media/'
    MEDIA_ROOT = f"/home/{os.environ.get('USER', 'username')}/Ayuda-RRHH-Usuarios/media"
    STATIC_URL = '/static/'
    STATIC_ROOT = f"/home/{os.environ.get('USER', 'username')}/Ayuda-RRHH-Usuarios/staticfiles"
    
    # Configuraciones de seguridad
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    
elif IS_RENDER:
    # Configuración para Render
    DEBUG = False
    ALLOWED_HOSTS = ['ayuda-rrhh-usuarios.onrender.com']
    CSRF_TRUSTED_ORIGINS = ['https://ayuda-rrhh-usuarios.onrender.com']
    
    # Configuraciones de seguridad para Render
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    USE_X_FORWARDED_HOST = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Media y static files para Render
    STATIC_URL = 'static/'
    STATICFILES_DIRS = [BASE_DIR / 'static']
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    
else:
    # Configuración para desarrollo local
    DEBUG = True
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    CSRF_TRUSTED_ORIGINS = ['http://localhost:8000']
    
    # Configuraciones de desarrollo
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    
    # Media y static files para desarrollo
    STATIC_URL = 'static/'
    STATICFILES_DIRS = [BASE_DIR / 'static']
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    
    # Nuestras apps
    'apps.empleados',
    'apps.documentos',
    'apps.solicitudes',
    'apps.notificaciones',
    'apps.rrhh',
    'apps.recibos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.empleados.middleware.CambioPasswordObligatorioMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proyecto_rrhh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'proyecto_rrhh.context_processors.empleado_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto_rrhh.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de Email
if IS_DEVELOPMENT:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# Login/Logout URLs
LOGIN_URL = '/empleados/login/'
LOGIN_REDIRECT_URL = '/empleados/dashboard/'
LOGOUT_REDIRECT_URL = '/empleados/login/'
