# Generated by Django 5.2.3 on 2025-07-01 15:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('telefono_emergencia', models.CharField(max_length=20)),
                ('contacto_emergencia', models.CharField(max_length=100)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('fecha_ingreso', models.DateField()),
                ('puesto', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('personal', 'Documento Personal'), ('laboral', 'Documento Laboral'), ('certificado', 'Certificado')], max_length=20)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado')),
            ],
            options={
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('alerta', 'Alerta'), ('recordatorio', 'Recordatorio')], default='info', max_length=20)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ReciboSueldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('periodo', models.CharField(max_length=20)),
                ('archivo', models.FileField(upload_to='recibos/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Firma'), ('firmado', 'Firmado'), ('disconformidad', 'Firmado en Disconformidad')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('observaciones_respuesta', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.tiposolicitud')),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
