# Generated by Django 5.2.3 on 2025-07-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='importante',
            field=models.BooleanField(default=False),
        ),
    ]
