# Generated by Django 5.2.3 on 2025-07-01 16:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilRRHH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(default='Recursos Humanos', max_length=100)),
                ('puede_aprobar_solicitudes', models.BooleanField(default=True)),
                ('puede_subir_recibos', models.BooleanField(default=True)),
                ('puede_gestionar_empleados', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[('recibo_subido', 'Recibo Subido'), ('solicitud_aprobada', 'Solicitud Aprobada'), ('solicitud_rechazada', 'Solicitud Rechazada'), ('empleado_creado', 'Empleado Creado'), ('empleado_editado', 'Empleado Editado'), ('notificacion_enviada', 'Notificación Enviada'), ('documento_subido', 'Documento Subido')], max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('empleado_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado')),
                ('usuario_rrhh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_rrhh.perfilrrhh')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AprobacionSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aprobacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentarios', models.TextField(blank=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.solicitud')),
                ('aprobador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_rrhh.perfilrrhh')),
            ],
        ),
    ]
